### PR TITLE
Add type definitions

### PR DESCRIPTION
**Pull request by Shadofer**
This pull request attempts to add types to the saos package

It also changes the structure quite a bit, moves from rollup to svelte-kit

### CODE REVIEW

**Comment by Shadofer** [comment]
Only problem is vs code complains about `$$prop_def` even though we use `SvelteComponentTyped`

**Comment by shiryel** [comment]
Thanks for the PR :heart:

I will take some time to test in the weekend

**Comment by Shadofer** [comment]
Any updates?

Just reinstall my whole OS so I may be of little help at the moment

**Comment by shiryel** [comment]
Didn't had time yet, unfortunately I had to fix my NixOS config and some backups this weekend :disappointed:

**Comment by Shadofer** [comment]
That's fine, linux norm

I'll try it myself once I reinstall my OS

**Comment by shiryel** [comment]
Finally, had time to review and test the code, sorry for the wait.

The code worked fine, I will just need to make some adjusts to the CI later, but anyway, thanks for the PR

:heart: :blue_heart: :green_heart: :purple_heart: :yellow_heart:

**Comment by Shadofer** [comment]
Lets go!

No worries, atleast we got it working!

**Pull request merged**
